### ISSUE TITLE
How do I apply for nico-opendata

### ISSUE THREAD

**Issue by aihao2000** [kcct-fujimotolab/nico-opendata-downloader#1]
Hello. How do I apply for nico-opendata? I hope to do some academic research

**Comment by fohte** [comment]
Thank you for reaching out! Unfortunately, I've not maintained this repository for 7 years, and I don't have plans to continue maintaining it in the future. I'll be archiving this repository soon.

My intention with this project was also for academic research, but I've since graduated and am no longer involved in that field.

For information on how to use nico-opendata, please refer to the official site: https://dmv.nico/ja/nico-opendata/
